org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.09.14

minecraft_version=1.21.8
minecraft_version_range=[1.21.8,1.22)
neo_version=21.8.53
neo_version_range=[21,)
loader_version_range=[4,)

mod_id=attributeslib
maven_artifact_id=attributeslib-neoforge
mod_name=AttributesLib
mod_license=Mozilla Public License 2.0
mod_version=1.21.8-1.0.0-SNAPSHOT
mod_group_id=io.github.hhoao
mod_authors=
mod_description=Library mod that provides extended attribute behavior, formatting, and attribute-related gameplay hooks.

java_version=21
